name: Deploy Vue CLI to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "juan.linares@geostudio.com.co"
          git config --global user.name "datasantana"
          git add dist -f
          git commit -m "Deploy Vue CLI to GitHub Pages"
          git push origin `git subtree split --prefix dist main`:refs/heads/gh-pages --force
